services:
  facetime-app:
    build:
      context: .  # Build from current directory
      dockerfile: Dockerfile
    container_name: facetime-app
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    restart: always # Restart on failure